im_size: [256, 256]  # Utilisation d'une liste au lieu d'un tuple pour YAML
input_shape : [256, 256 ,3]
num_epochs: 50
batch_size: 8
test_split: 0.2
base_learning_rate: 1e-3
random_state: 42
noise_factor: 0.3
