artifacts_root: artifacts

data_ingestion:
  images_dir: ['D:\data\Grape___Black_rot']
  root_dir: "artifacts/data_ingestion"
  train_data_path: "artifacts/data_ingestion/train.npy"
  test_data_path: "artifacts/data_ingestion/test.npy"

data_preprocessing:
  root_dir: "artifacts/data_preprocessing"
  x_train_noisy_path: "artifacts/data_preprocessing/train_noisy.npy"
  x_test_noisy_path: "artifacts/data_preprocessing/test_noisy.npy"

base_model:
  root_dir: "artifacts/base_model"
  base_model_path: "artifacts/base_model/Autoencoder_Denoising_model.keras"
  updated_base_model_path: "artifacts/base_model/Autoencoder_Denoising_model.keras"

training:
  root_dir: "artifacts/training"
  train_model_path: "artifacts/training/Autoencoder_Denoising_model.keras"

evaluation:
    root_dir: "artifacts/model_evaluation"
    evaluation_report_path: "artifacts/model_evaluation/evaluation_report.json"

